name: gesture_recorder
description:
  A tool to record gestures for a flutter app for generating a test case, and
  for replaying the recorded gestures for test purposes.
version: 0.0.2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

dev_dependencies:
  flutter_lints: ^1.0.4
